vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        post_thumbnail:
            uri_prefix: /images
            upload_destination: "%kernel.project_dir%/public/images/knife"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer